#Spring
spring:
  application:
    name: file-processing-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://postgres:5432/file_processing?createDatabaseIfNotExist=true&currentSchema=file_processing
    username: admin
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        default_schema: file_processing
        show_sql: true
      jakarta:
        persistence:
          create-database-schemas: true
      flyway:
        default-schema: file_processing
        enabled: true

  #Kafka
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: file-processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      concurrency: 1
#Logging
logging:
  level:
    org:
      springframework: INFO

#Custom
external:
  service:
    base-url: https://202b27fd-cb6e-45fe-ba97-5549424307fe.mock.pstmn.io
    receive-users-url: /users/receive
file:
  processing:
    topic: file-processing-topic
  supported:
    type: .csv
    size: 10485760
  time-restrictions:
    start: "22:00"
    end: "08:00"
